"""Catalogue central des permissions fonctionnelles et profils initiaux."""

PERMISSIONS = {
    "dashboard.read": ("Consulter le tableau de bord métier", "Tableau de bord"),
    "admin.dashboard.read": ("Consulter le tableau de bord administratif", "Administration"),
    "saisie_caisse.read": ("Consulter les écritures de caisse", "Saisie caisse"),
    "saisie_caisse.crud_ecriture_caisse_manage": (
        "Gérer les écritures de caisse (création, modification, suppression et migration SAGE)",
        "Saisie caisse",
    ),
    "saisie_caisse.cleanup": ("Nettoyer les anciennes écritures déjà migrées vers SAGE", "Saisie caisse"),
    "export_csv.caisse": ("Exporter les écritures de caisse", "Exports"),
    "export_csv.brouillard": ("Exporter le brouillard de caisse", "Exports"),
    "saisie_bancaire.import": ("Importer un relevé bancaire", "Saisie bancaire"),
    "saisie_bancaire.sessions.read": ("Consulter et reprendre les sessions", "Saisie bancaire"),
    "saisie_bancaire.entries.manage": ("Modifier et enregistrer les lignes", "Saisie bancaire"),
    "saisie_bancaire.sage.generate": ("Générer les écritures SAGE", "Saisie bancaire"),
    "saisie_bancaire.sage.export": ("Exporter le fichier SAGE", "Saisie bancaire"),
    "rapprochement_bancaire.run": ("Lancer un rapprochement bancaire", "Rapprochement bancaire"),
    "rapprochement_bancaire.export_pdf": ("Exporter le rapprochement en PDF", "Rapprochement bancaire"),
    "sage_bfc.read": ("Consulter toutes les parties d'analyse SAGE → BFC", "SAGE → BFC"),
    "sage_bfc.import": ("Importer une balance SAGE", "SAGE → BFC"),
    "sage_bfc.month.delete": ("Supprimer une période", "SAGE → BFC"),
    "sage_bfc.year.close": ("Clôturer une année", "SAGE → BFC"),
    "forecast.read": ("Consulter les prévisions", "Forecast"),
    "forecast.generate": ("Générer le budget initial", "Forecast"),
    "forecast.cycle.run": ("Exécuter un cycle Forecast", "Forecast"),
    "forecast.manual.update": ("Modifier manuellement les prévisions", "Forecast"),
    "forecast.history.import": ("Importer l'historique Forecast", "Forecast"),
    "forecast.history.sync": ("Synchroniser les années clôturées", "Forecast"),
    "reporting.read": ("Consulter et prévisualiser le reporting", "Reporting"),
    "reporting.export_excel": ("Exporter le reporting en Excel", "Reporting"),
    "reporting.export_pdf": ("Exporter le reporting en PDF", "Reporting"),
    "reporting.print": ("Imprimer le reporting", "Reporting"),
    "configuration.accounts.read": ("Consulter les comptes", "Configuration"),
    "configuration.accounts.manage": ("Ajouter et modifier les comptes", "Configuration"),
    "configuration.accounts.delete": ("Supprimer les comptes", "Configuration"),
    "configuration.third_parties.read": ("Consulter les tiers", "Configuration"),
    "configuration.third_parties.manage": ("Ajouter et modifier les tiers", "Configuration"),
    "configuration.third_parties.delete": ("Supprimer les tiers", "Configuration"),
    "configuration.mapping.read": ("Consulter le mapping SAGE → BFC", "Configuration"),
    "configuration.mapping.manage": ("Ajouter et modifier le mapping et ses règles", "Configuration"),
    "configuration.mapping.delete": ("Supprimer un mapping", "Configuration"),
    "admin.users.read": ("Consulter les utilisateurs", "Administration"),
    "admin.users.manage": ("Créer et modifier les utilisateurs", "Administration"),
    "admin.users.activate": ("Activer ou désactiver un utilisateur", "Administration"),
    "admin.users.reset_password": ("Réinitialiser les mots de passe", "Administration"),
    "admin.users.revoke_sessions": ("Révoquer les sessions", "Administration"),
    "admin.users.delete": ("Supprimer définitivement un utilisateur", "Administration"),
    "admin.roles.read": ("Consulter les profils et permissions", "Administration"),
    "admin.roles.manage": ("Configurer les profils et permissions", "Administration"),
    "admin.audit.read": ("Consulter le journal d'audit", "Administration"),
    "admin.audit.delete": ("Purger le journal d'audit", "Administration"),
}


PROFILES = {
    "COMPTABLE": (
        "Comptable",
        "Saisie comptable, opérations bancaires et préparation des exports.",
        {
            "dashboard.read", "saisie_caisse.read",
            "saisie_caisse.crud_ecriture_caisse_manage",
            "export_csv.caisse", "export_csv.brouillard", "saisie_bancaire.import",
            "saisie_bancaire.sessions.read", "saisie_bancaire.entries.manage",
            "saisie_bancaire.sage.generate", "saisie_bancaire.sage.export",
            "rapprochement_bancaire.run", "rapprochement_bancaire.export_pdf",
            "sage_bfc.read", "sage_bfc.import",
        },
    ),
    "FINANCIER": (
        "Financier",
        "Pilotage BFC, Forecast et Reporting.",
        {
            "dashboard.read", "sage_bfc.read", "sage_bfc.import",
            "sage_bfc.month.delete", "sage_bfc.year.close", "forecast.read",
            "forecast.generate", "forecast.cycle.run", "forecast.manual.update",
            "forecast.history.import", "forecast.history.sync", "reporting.read",
            "reporting.export_excel", "reporting.export_pdf", "reporting.print",
            "configuration.accounts.read", "configuration.third_parties.read",
            "configuration.mapping.read",
        },
    ),
    "DIRIGEANT": (
        "Dirigeant",
        "Consultation des indicateurs, analyses et rapports.",
        {
            "dashboard.read", "sage_bfc.read", "forecast.read", "reporting.read",
            "reporting.export_excel", "reporting.export_pdf", "reporting.print",
        },
    ),
    "ADMIN_FONCTIONNEL": (
        "Administrateur fonctionnel",
        "Administration des référentiels et mappings métier.",
        {
            "dashboard.read", "configuration.accounts.read", "configuration.accounts.manage",
            "configuration.accounts.delete", "configuration.third_parties.read",
            "configuration.third_parties.manage", "configuration.third_parties.delete",
            "configuration.mapping.read", "configuration.mapping.manage",
            "configuration.mapping.delete",
        },
    ),
    "SUPER_ADMIN": (
        "Super administrateur",
        "Administration technique des utilisateurs, profils et journaux.",
        {code for code in PERMISSIONS if code.startswith("admin.")},
    ),
}
